### ISSUE TITLE
Warning: curl_setopt(): 293 is not a valid cURL handle resource

### ISSUE THREAD

**Issue by ddeboer** [BeSimple/BeSimpleSoapClient#6]
The following errors seems to occur when issuing multiple requests to a SOAP web service.

```
PHP Fatal error:  Uncaught exception 'ErrorException' with message 'Warning: curl_setopt(): 293 is not a valid cURL handle resource in XYZ/vendor/besimple/soap-client/src/BeSimple/SoapClient/Curl.php line 121' in XYZ/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Debug/ErrorHandler.php:65
Stack trace:
#0 [internal function]: Symfony\Component\HttpKernel\Debug\ErrorHandler->handle(2, 'curl_setopt(): ...', 'XYZ...', 121, Array)
#1 XYZ/vendor/besimple/soap-client/src/BeSimple/SoapClient/Curl.php(121): curl_setopt(Resource id #293, 10002, 'https://eu1-api...')
#2 XYZ/vendor/besimple/soap-client/src/BeSimple/SoapClient/SoapClient.php(137): BeSimple\SoapClient\Curl->exec('https://eu1-api...', '<?xml version="...', Array)
#3 XYZ/vendor/besimple/soap-client/src/BeSimple/SoapClient/SoapClient.php(204): BeSimple\SoapClient\SoapClient->__doHttpRequest(Object(BeSimple\SoapClient\SoapRequest))
#4 XYZ/vendor/besimple/soap-cli in XYZ/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Debug/ErrorHandler.php on line 65
```

**Comment by aschamberger** [comment]
I can't reproduce this error. Can you post some code to reproduce it?

**Comment by ddeboer** [comment]
Sorry, this was a problem in my application where I had some code in a `__destruct()` method that executed a call through the BeSimple client. In this case, the curl handler had apparently already been closed.
